### ISSUE TITLE
Quick question about the Lang Menu.

### ISSUE THREAD

**Issue by crochefort** [wet-boew/theme-gc-intranet#124]
Is it normal that all the LI in the following code 

```html 
<section id="wb-lng"><h2>Sélection de la langue</h2>
<ul class="list-inline">
<li><a lang="en" href="index-en.html">English</a></li>
</ul>
</section>
``` 
don't separate the lang(li) like in the GCWU theme?

By adding a border-left?

```css
@media screen and (min-width: 992px)
#gc-bar a {
border-left: 1px solid #fff;
padding: 0 .5em;
}
```

Right now if you add more LI we don't see visual separation.
